all:
	gcc -std=c99 -W -Wall -Wextra -pedantic -Wcast-align -Wcast-qual\
	    -Wconversion -Wwrite-strings -Wfloat-equal -Wlogical-op -Wpointer-arith\
	    -Wformat=2 -Winit-self -Wuninitialized -Wmaybe-uninitialized -Wshadow\
	    -Wstrict-prototypes -Wmissing-declarations -Wmissing-prototypes -Werror\
	    consume.c -lmpdclient -o consume
