#!/usr/bin/env sh
# Creates a VDE switch according to the settings in /etc/conf.d/vde and
# configures its tap interface according to /etc/dnsmasq.conf.

appname="$0"
vde_conf='/etc/conf.d/vde'
dnsmasq_conf='/etc/dnsmasq.conf'
vde_rundir='/run/vde'
vde_runfile="$vde_rundir/vde.run"

# Default configuration:
VDE_TAP='vde0'
VDE_TAP_IP='192.168.0.1'
VDE_TAP_NETMASK='24'
VDE_SOCK_MODE='660'
VDE_SOCK_GROUP='root'

vde_checkroot() {
	if [ $(id -u) -ne 0 ]; then
		echo "Must be root to run $appname" >&2
		exit 1
	fi
}

vde_start() {
	# Get user configuration:
	if [ ! -e "$vde_conf" ]; then
		echo "$vde_conf not found, using default configuration" >&2
	else
		. "$vde_conf"
	fi
	if [ ! -e "$dnsmasq_conf" ]; then
		echo "$dnsmasq_conf not found, using default IP" >&2
	else
		vde_tap_ip_tmp="$(grep '^dhcp-range=' "$dnsmasq_conf" | head -n 1 | \
		                  sed -e 's/^dhcp-range=//g' | cut -d ',' -f 1)"
		if [ -z "$vde_tap_ip_tmp" ]; then
			echo "$dnsmasq_conf: no DHCP range specified, using default range" \
			     >&2
		else
			VDE_TAP_IP="$vde_tap_ip_tmp"
		fi
	fi

	# Start VDE switch:
	echo "tap=${VDE_TAP}, mode=${VDE_SOCK_MODE}, group=${VDE_SOCK_GROUP}"
	vde_switch --daemon \
			   --tap ${VDE_TAP} \
			   --mode ${VDE_SOCK_MODE} --group ${VDE_SOCK_GROUP}

	# Bring up tap interface and assign IP address:
	ip link set dev "${VDE_TAP}" up
	ip addr add "${VDE_TAP_IP}/${VDE_TAP_NETMASK}" dev "${VDE_TAP}"

	# Store IP:
	mkdir -p "$vde_rundir"
	echo "VDE_TAP=${VDE_TAP}" > "$vde_runfile"
	echo "VDE_TAP_IP=${VDE_TAP_IP}/${VDE_TAP_NETMASK}" >> "$vde_runfile"
}

vde_stop() {
	# Bring down tap interface:
	if [ ! -e "$vde_runfile" ]; then
		echo "$vde_runfile not found, cannot delete IP address" >&2
	else
		. "$vde_runfile"
		ip addr del ${VDE_TAP_IP} dev ${VDE_TAP}
		ip link set dev ${VDE_TAP} down
		rm "$vde_runfile"
		rmdir --ignore-fail-on-non-empty "$vde_rundir"
	fi

	# Kill VDE switch:
	killall vde_switch
}

vde_help() {
	echo "Usage: $appname start|stop" >&2
	exit -1
}

case "$1" in
	start) vde_checkroot; vde_start ;;
	stop) vde_checkroot; vde_stop ;;
	*) vde_help ;;
esac
