#!/bin/sh
# This script handles a VLS (Virtual Local Server), a headless qemu VM hooked up
# to a VDE switch.
# It assumes that dnsmasq is already running (see vls.service).

appname="$0"
dnsmasq_conf='/etc/dnsmasq.conf'

# Default configuration:
VLS_MAC='52:54:00:12:34:56'

vls_start() {
	# Get dnsmasq configuration for static IPs:
	if [ ! -e "$dnsmasq_conf" ]; then
		echo "$dnsmasq_conf not found, using default MAC address" >&2
	else
		vls_mac_tmp="$(grep '^dhcp-host=' "$dnsmasq_conf" | head -n 1 | \
		               sed -e 's/^dhcp-host=//g' | cut -d ',' -f 1)"
		VLS_MAC="$vls_mac_tmp"
	fi
	qemu-system-x86_64 \
		-enable-kvm -cpu host -smp 4 \
		-m 4096 \
		-drive file=/home/ayekat/.local/share/qemu/debian/debian.raw \
		-net nic,model=virtio,macaddr=${VLS_MAC} -net vde \
		-nographic -vnc :7 \
		-monitor unix:/tmp/vls.sock,server,nowait &
}

vls_stop() {
	echo "system_powerdown" | socat stdio /tmp/vls.sock
	rm -f /tmp/vls.sock
}

vls_help() {
	echo "Usage: $appname start|stop" >&2
	exit 1
}

case "$1" in
	start) vls_start ;;
	stop) vls_stop ;;
	*) vls_help ;;
esac
