#!/bin/sh
# Xinit ressource file for starting dwm
# Written by ayekat on a rainy day in october 2012

cmds_exist() {
	for c in "$@"; do
		which "$c" >/dev/null 2>&1 || return 1
	done
}


# First of all, make sure we are in the home directory, to avoid weird default
# working directory paths when opening a shell under X:
cd


# SYSTEM-WIDE ------------------------------------------------------------------

system_xinit=/etc/X11/xinit/xinitrc.d
if [ -d "$system_xinit" ]; then
	for f in "$system_xinit"/*; do
		if [ -r "$f" ]; then
			. "$f"
		fi
	done
	unset f
fi
unset system_xinit


# INPUT/OUTPUT -----------------------------------------------------------------

if cmds_exist xinput xmodmap; then
	case "$(hostname)" in
		ixh) ayeinput -em ;;
		*) ayeinput -e ;;
	esac
fi
cmds_exist dispwin && lcdadjust


# SERVICES ---------------------------------------------------------------------

# Load X resources:
cmds_exist xrdb && xrdb "$XDG_CONFIG_HOME/X11/Xresources"

# Start a scratchpad:
cmds_exist urxvt && urxvt -e tmx SCRATCHPAD &

# Set the wallpaper:
cmds_exist nitrogen && nitrogen --restore

# Enable Japanese input:
if cmds_exist uim-xim; then
	export GTK_IM_MODULE=uim
	export QT_IM_MODULE=uim
	uim-xim &
	export XMODIFIERS='@im=anthy'
fi


# WM ---------------------------------------------------------------------------

# If no WM is specified, default to karuiwm:
[ -z "$WM" ] && WM=karuiwm

# Some Java applications refuse to work correctly when they don't know the WM
# (happens often with tiling WMs); set the WM name to a value known to Java to
# fix that:
if cmds_exist wmname; then
	case "$WM" in
		xmonad|dwm|karuiwm) wmname LG3D ;;
	esac
fi

# Launch WM and log all of its output:
SESSION_LOGDIR="$XDG_LOG_HOME/X11/$DISPLAY"
SESSION_LOGFILE="${SESSION_LOGDIR}/$(date +%s).log"
mkdir -p "$SESSION_LOGDIR"
ln -sf "$SESSION_LOGFILE" "$SESSION_LOGDIR/latest"
while true; do
	if cmds_exist karuibar; then
		karuibar &
		KARUIBAR_PID=$!
	fi

	if cmds_exist xss-lock scrlock; then
		xset s 300
		xss-lock scrlock &
		XSS_LOCK_PID=$!
	fi

	"$WM"

	cmds_exist xss-lock && kill $XSS_LOCK_PID
	cmds_exist karuibar && kill $KARUIBAR_PID

	if cmds_exist zenity; then
		zenity --question --text="$WM has stopped. Do you want to start again?"
		test $? -eq 0 || break
	else
		break
	fi
done >"$SESSION_LOGFILE" 2>"$SESSION_LOGFILE"
