#!/usr/bin/env sh
# Environment set when logging into a shell.
# Written by ayekat on a frustrating evening in september 2014.

# ------------------------------------------------------------------------------
# OPERATING SYSTEM {{{

OS_RELEASE=''
if [ -e /etc/lsb-release ]; then
	OS_RELEASE="$(grep -e '^DISTRIB_ID=' /etc/lsb-release | cut -d '=' -f 2 | \
	              tr '[:upper:]' '[:lower:]')"
elif [ -e /etc/os-release ]; then
	OS_RELEASE="$(grep -e '^ID=' /etc/os-release | cut -d '=' -f 2)"
elif [ "$(uname)" = 'Darwin' ]; then
	OS_RELEASE='darwin'
elif [ -e /etc/gentoo-release ]; then
	OS_RELEASE='gentoo'
elif [ -e /etc/arch-release ]; then
	OS_RELEASE='arch'
elif [ -e /etc/debian_version ]; then
	OS_RELEASE='debian'
else
	OS_RELEASE="$(uname)"
fi
export OS_RELEASE

# }}}
# ------------------------------------------------------------------------------
# PATH {{{

# Check if directory is already in PATH:
path_lacks() {
	case "$OS_RELEASE" in
		darwin) READLINK=greadlink ;;
		*) READLINK=readlink ;;
	esac
	for i in $PATH; do
		[ "$1" != "$i" ] || return 1
		[ ! -h "$1" ] || [ "$($READLINK -f "$1")" != "$i" ] || return 1
	done
}

# Add directory to PATH (if existing and not duplicate):
add_to_path() {
	[ -d "$1" ] || return
	[ -z "$PATH" ] && PATH="$1" && return
	IFS_OLD="$IFS"
	IFS=:
	if path_lacks "$1"; then
		if [ "$2" = '--append' ]; then
			PATH="$PATH:$1"
		else
			PATH="$1:$PATH"
		fi
	fi
	IFS="$IFS_OLD"
	unset IFS_OLD
}

# Basic paths (no /usr merge because of Debian; this diverges from the
# "traditional" order):
add_to_path '/sbin'
add_to_path '/usr/sbin'
add_to_path '/usr/local/sbin'

# User specific path:
add_to_path "$HOME/.local/bin"

# EPFL scripts:
add_to_path "$HOME/.local/opt/epflscripts/bin"

# Altera (Quartus, ModelSim):
# - user is recommended to be in 'plugdev' group, for USB devices
# - quartus starts Quartus, vsim starts ModelSim
dir_altera="$HOME/.local/opt/altera"
if [ -d "$dir_altera" ]; then
	for p in "$dir_altera/nios2eds/bin/gnu/H-$(uname -m)-pc-linux-gnu/bin" \
	         "$dir_altera/nios2eds/sdk2/bin" \
	         "$dir_altera/nios2eds/bin" \
	         "$dir_altera/quartus/bin" \
	         "$dir_altera/quartus/sopc_builder/bin" \
	         "$dir_altera/modelsim_ase/bin"
	do
		add_to_path "$p" --append
	done
	export QUARTUS_ROOTDIR="$dir_altera/quartus"
	export SOPC_KIT_NIOS2=/home/ayekat/.local/opt/altera/nios2eds
	if [ "$(uname -m)" = 'x86_64' ]; then
		export QUARTUS_64BIT=1
	else
		export QUARTUS_64Bit=0
	fi
fi
unset dir_altera

unset -f path_lacks
unset -f add_to_path
export PATH

# }}}
# ------------------------------------------------------------------------------
# DEFAULT APPLICATIONS {{{

# Editor and pager:
export EDITOR='/usr/bin/vim'
export VISUAL='/usr/bin/vim'
export PAGER='/usr/bin/less'

# }}}
# ------------------------------------------------------------------------------
# LOOK {{{

# Set hinting property for freetype (see /etc/profile.d/freetype2.sh):
export FREETYPE_PROPERTIES='truetype:interpreter-version=35'

# Set output style for `ls` in coreutils>=8.25:
export QUOTING_STYLE=literal

# Set colours for ls:
export LS_COLORS='fi=0:di=34:ex=32:ln=36:or=1;36:mi=1;31:bd=1;33:cd=33:pi=35:so=1;35'
#                 file dir   exec  link  orphan          block   char  fifo  socket

# Set colours for gcc:
export GCC_COLORS='error=01;31:warning=33:note=36:caret=01;32:locus=37:quote=32'

# Set colours for less, man:
LESS_TERMCAP_me="$(printf "\033[0m")"
LESS_TERMCAP_se="$(printf "\033[0m")"
LESS_TERMCAP_so="$(printf "\033[30;43m")"
LESS_TERMCAP_ue="$(printf "\033[0m")"
LESS_TERMCAP_us="$(printf "\033[32m")"
LESS_TERMCAP_mb="$(printf "\033[34m")"
LESS_TERMCAP_md="$(printf "\033[31m")"
export LESS_TERMCAP_mb
export LESS_TERMCAP_md
export LESS_TERMCAP_me
export LESS_TERMCAP_se
export LESS_TERMCAP_so
export LESS_TERMCAP_ue
export LESS_TERMCAP_us

# }}}
# ------------------------------------------------------------------------------
# RAINBOWDASH FUCK-AROUND {{{
# GNU Generation server admin thinks it's funny to have a french locale.

if [ "$(hostname)" = 'rainbowdash' ] && locale -a |grep 'en_GB\.utf8' >/dev/null
then
	export LANG=en_GB.utf8
fi

# }}}
