#!/bin/sh
# Xinit ressource file for starting dwm
# Written by ayekat on a rainy day in october 2012


# First of all, make sure we are in the home directory, to avoid weird default
# working directory paths when opening a shell under X:
cd

if [ -n "$REMOTE" ]; then
	ssh -X "$REMOTE" .config/X11/xinitrc
	exit
fi

# INPUT ------------------------------------------------------------------------

ayeinput --mouse swap --scroll middle


# OUTPUT -----------------------------------------------------------------------

# Enable colour profile:
lcdadjust &


# SERVICES ---------------------------------------------------------------------

# Load X resources:
xrdb ~/.config/X11/Xresources

# Start a scratchpad:
urxvt -e tmx SCRATCHPAD &

# Set the wallpaper:
nitrogen --restore

# Activate Japanese input:
if [ -e /usr/bin/uim-xim ]; then
	export GTK_IM_MODULE=uim
	export QT_IM_MODULE=xim
	export QT4_IM_MODULE=uim
	export QT5_IM_MODULE=xim
	export XMODIFIERS=@im='anthy'
	uim-xim &
fi

# Enable automatic lock on timeout:
scrock --daemon start

# Launch status bar:
#karuibar &


# WM ---------------------------------------------------------------------------

# If no WM is specified, default to karuiwm:
[ -z "$WM" ] && WM=karuiwm

# Some Java applications refuse to work correctly when they don't know the WM
# (happens often with tiling WMs); set the WM name to a value known to Java to
# fix that:
case "$WM" in
	xmonad|dwm|karuiwm) wmname LG3D ;;
esac

# Launch WM and log all of its output:
while true; do
	"$WM"
	zenity --question --text="$WM has stopped. Do you want to start again?"
	test $? -eq 0 || break
done > /tmp/xorg-"$USER"-"$DISPLAY".log 2>&2
