#!/bin/sh
# Xinit ressource file for starting dwm
# Written by ayekat on a rainy day in october 2012


# First of all, make sure we are in the home directory, to avoid weird default
# working directory paths when opening a shell under X:
cd

if [ -n "$REMOTE" ]; then
	ssh -X "$REMOTE" .config/X11/xinitrc
	exit
fi

# INPUT (KEYBOARD) -------------------------------------------------------------

# Load swiss keyboard layout; then apply a few modifications:
setxkbmap -layout ch -option caps:swapescape
xmodmap ~/.config/X11/xmodmaprc


# INPUT (MOUSE) ----------------------------------------------------------------

# Thinkpad mouse:
if [ $(hostname) = 'ixh' ]; then
	dev='TPPS/2 IBM TrackPoint'
	ptr='3 2 1 4 5 6 7 8 9 10'
	tmo='200'
else
	dev='pointer:Lenovo ThinkPad Compact USB Keyboard with TrackPoint'
	ptr='3 2 1 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22'
	tmo='0'
fi

# Swap left and right button:
xmodmap -e "pointer = $ptr"

# Enable scrolling through middle click + trackpad:
xinput set-prop "$dev" 'Evdev Wheel Emulation' 1
xinput set-prop "$dev" 'Evdev Wheel Emulation Button' 2
xinput set-prop "$dev" 'Evdev Wheel Emulation Axes' 6 7 4 5
xinput set-prop "$dev" 'Evdev Wheel Emulation Timeout' $tmo

# Enable middle click drag&drop (work-around for above option):
xinput set-prop "$dev" 'Evdev Middle Button Emulation' 1


# OUTPUT -----------------------------------------------------------------------

# Enable colour profile:
lcdadjust &


# SERVICES ---------------------------------------------------------------------

# Load X resources:
xrdb ~/.config/X11/Xresources

# Start a scratchpad:
urxvt -e tmx SCRATCHPAD &

# Set the wallpaper:
nitrogen --restore

# Activate Japanese input:
if [ -e /usr/bin/uim-xim ]; then
	export GTK_IM_MODULE='uim'
	export XMODIFIERS=@im='anthy'
	uim-xim &
fi

# Enable automatic lock on timeout:
scrock --daemon start

# Launch status bar:
karuibar &


# WM ---------------------------------------------------------------------------

# If no WM is specified, default to karuiwm:
[ -z "$WM" ] && WM=karuiwm

# Some Java applications refuse to work correctly when they don't know the WM
# (happens often with tiling WMs); set the WM name to a value known to Java to
# fix that:
case "$WM" in
	xmonad|dwm|karuiwm) wmname LG3D ;;
esac

# Launch WM and log all of its output:
while true; do
	"$WM" > /tmp/xorg-"$USER"-"$DISPLAY".log 2>&1
	zenity --question --text="$WM has stopped. Do you want to start again?"
	test $? -eq 0 || break
done
