#!/bin/sh
# scrock (screen lock) configuration file.
# See https://github.com/ayekat/dotfiles/tree/master/.local/src/scrock for more
# information.

# Command to be run when scrock is started (MANDATORY):
SCROCK_CMD='i3lock -n -c 000000 -i /home/ayekat/img/wallpapers/Avengers_Minions_1366.png'
# Examples:
#SCROCK_CMD='i3lock -n -c 000000 -i /path/to/wallpaper.png'
#SCROCK_CMD=slock
#SCROCK_CMD=xtrlock
#SCROCK_CMD='xscreensaver-command -lock'

# PID file:
SCROCK_PID=/tmp/scrock.pid

# Disable dunst while running the screen lock programme?
SCROCK_DUNST=1

# Idle time (in minutes) until automatic lock (for daemon mode):
SCROCK_IDLE=5

# Mouse device (get name with 'xinput list'):
SCROCK_MOUSE='TPPS/2 IBM TrackPoint'
# Examples:
#SCROCK_MOUSE='TPPS/2 IBM TrackPoint'
