#!/bin/sh
# Opens files with a default programme according to its MIME type.
# Written by ayekat on a cold morning in september 2014.

[ -n "$XDG_CONFIG_HOME" ] || XDG_CONFIG_HOME=~/.config
confdir="$XDG_CONFIG_HOME/open"
conffile="$confdir/openrc"

#-------------------------------------------------------------------------------

# Create empty configuration file.
create_empty_config() {
	cat >"$conffile" <<- EOF
	# MIME mapping configuration file
	placeholder : _FILE_
	EOF
}

file_not_found() {
	echo "open: $1: file not found" >&2
	exit_value=1
}

mime_not_found() {
	echo "open: $1: default application not specified" >&2
	exit_value=1
}

# Determine if a file is actually a URI.
is_uri() {
	echo "$1" | grep -q '^[a-zA-Z0-9]\+:/'
}

# Get value for a key.
value_of() {
	line="$(grep "^[ \t]*$1[ \t]*:[ \t]*[^ \t]\\+" "$conffile")"
	if [ -n "$line" ]; then
		echo "$line" | sed -e 's/^[^:]*:[ \t]*//' -e 's/[ \t]*$//'
	else
		echo ''
	fi
}

# Get procotol of a URI.
get_protocol() {
	echo "$1" | grep -o '^[a-zA-Z0-9]\+'
}

# Get MIME type for a file.
get_mime() {
	file="$1"
	mime="$(file --dereference --mime-type --brief "$file")"
	if [ "$mime" = 'application/octet-stream' ]; then
		x="$(echo "$file" | awk -F . '{print $NF}')"
		m="$(value_of ".$x")"
		[ -n "$m" ] && mime="$m"
	fi
	echo "$mime"
}

# Assemble commandline for a file.
assemble_command() {
	file="$1"
	if is_uri "$file"; then
		protocol="$(get_protocol "$file")"
		mime="$(value_of "$protocol")"
	elif [ -e "$file" ]; then
		mime="$(get_mime "$file")"
	else
		file_not_found "$file"
		return
	fi

	cmd="$(value_of "$mime")"
	if [ -z "$cmd" ]; then
		[ -n "$protocol" ] && mime="$protocol:/"
		mime_not_found "$mime"
		echo ''
	else
		if [ -n "$placeholder" ] && echo "$cmd" | grep -q "$placeholder"; then
			fsan="$(echo "$1" | sed -e 's/\//\\\//g')"
			echo "$cmd" | sed -e "s/$placeholder/\"$fsan\"/g"
		else
			echo "$cmd \"$file\""
		fi
	fi
}

#-------------------------------------------------------------------------------

# by default, we're successful
exit_value=0

# check whether configuration exists
[ -d "$confdir" ] || mkdir "$confdir"
[ -f "$conffile" ] || create_empty_config

# determine placeholder sequence
placeholder="$(value_of 'placeholder')"

if [ $# -eq 0 ]; then
	assemble_command '.' | sh
else
	for f in "$@"; do
		assemble_command "$f" | sh
	done
fi

exit $exit_value
