#!/usr/bin/env sh
# Environment set when logging into a shell.
# Written by ayekat on a frustrating evening in september 2014.

# ------------------------------------------------------------------------------
# PATH {{{

# Adds directory to the PATH variable, with (hopefully) all necessary checks:
add_to_path() {
	[ -d "$1" ] || return
	[ -z "$PATH" ] && PATH="$1" && return
	ifs_old="$IFS"
	IFS=:
	for i in $PATH; do
		[ "$1" = "$i" ] && return
		[ -h "$1" ] && [ "$(readlink -f "$1")" = "$i" ] && return
	done
	PATH="$1:$PATH"
	IFS="$ifs_old"
	unset ifs_old
}

# User specific path:
add_to_path "$HOME/.local/bin"

# Altera (Quartus, ModelSim):
# - user is recommended to be in 'plugdev' group, for USB devices
# - quartus starts Quartus, vsim starts ModelSim
dir_altera="$HOME/.local/altera"
if [ -d "$dir_altera" ]; then
	for p in "$dir_altera/quartus/bin" \
	         "$dir_altera/modelsim_ase/bin" \
	         "$dir_altera/nios2eds/bin" \
	         "$dir_altera/nios2eds/bin/gnu/H-i686-pc-linux-gnu/bin" \
	         "$dir_altera/nios2eds/sdk2/bin"
	do
		add_to_path "$p"
	done
fi
unset dir_altera

unset -f add_to_path
export PATH

# }}}
# ------------------------------------------------------------------------------
# XDG {{{

# Set XDG variables:
export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME=~/.cache
export XDG_DATA_HOME=~/.local/share

# Fix various applications to respect XDG:
export VIMINIT="source $XDG_CONFIG_HOME/vim/vimrc"    # vim
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"         # xinit (startx ignores)
export XAUTHORITY="$XDG_CACHE_HOME/X11/Xauthority"    # startx
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"             # gpg
export PGPPATH="$XDG_CONFIG_HOME/gnupg"               # mutt (pgp)
export TASKDATA="$XDG_DATA_HOME/task"                 # task-warrior
export TASKRC="$XDG_CONFIG_HOME/task/taskrc"          # task-warrior
export RXVT_SOCKET="$HOME/.urxvtd.sock"               # urxvtd
export LESSHISTFILE="$XDG_CACHE_HOME/lesshist"        # less
export PASSWORD_STORE_DIR="$XDG_CONFIG_HOME/pass"     # pass
export GIMP2_DIRECTORY="$XDG_CONFIG_HOME/gimp"        # gimp
export MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"        # mplayer

# }}}
# ------------------------------------------------------------------------------
# DEFAULT APPLICATIONS {{{

# Editor and pager:
export EDITOR='/usr/bin/vim'
export VISUAL='/usr/bin/vim'
export PAGER='/usr/bin/less'

# }}}
# ------------------------------------------------------------------------------
# LOOK {{{

# Set colours for less, man:
if [ "$TERM" = 'linux' ]; then
	export LESS_TERMCAP_mb=$(printf "\033[34m")
	export LESS_TERMCAP_md=$(printf "\033[31m")
	export LESS_TERMCAP_me=$(printf "\033[0m")
	export LESS_TERMCAP_se=$(printf "\033[0m")
	export LESS_TERMCAP_so=$(printf "\033[30;43m")
	export LESS_TERMCAP_ue=$(printf "\033[0m")
	export LESS_TERMCAP_us=$(printf "\033[32m")
else
	export LESS_TERMCAP_mb=$(printf "\033[1;34m")
	export LESS_TERMCAP_md=$(printf "\033[38;5;9m")
	export LESS_TERMCAP_me=$(printf "\033[0m")
	export LESS_TERMCAP_se=$(printf "\033[0m")
	export LESS_TERMCAP_so=$(printf "\033[30;43m")
	export LESS_TERMCAP_ue=$(printf "\033[0m")
	export LESS_TERMCAP_us=$(printf "\033[38;5;10m")
fi

# Set colours for ls (TODO):
#export LS_COLORS=''

# Set colours for gcc:
export GCC_COLORS='error=01;31:warning=33:note=36:caret=01;32:locus=37:quote=32'

# }}}
# ------------------------------------------------------------------------------
# OPERATING SYSTEM {{{

OS_RELEASE=''
if [ -e /etc/os-release ]; then
	OS_RELEASE="$(grep -e '^ID=' /etc/os-release | cut -c 4-)"
elif [ "$(uname)" = 'Darwin' ]; then
	OS_RELEASE='darwin'
elif [ -e /etc/gentoo-release ]; then
	OS_RELEASE='gentoo'
fi
export OS_RELEASE

# }}}
# ------------------------------------------------------------------------------
# RAINBOWDASH FUCK-AROUND {{{
# GNU Generation server admin thinks it's funny to have a french locale.

if [ $(hostname) = 'rainbowdash' ] && locale -a | grep 'en_GB\.utf8' >/dev/null
then
	export LANG=en_GB.utf8
fi

# }}}
