#!/bin/sh
# Sets environment variables before logging into the shell.

# Basic paths:
PATH=''
for p in /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin; do
	if [ -d "$p" ]; then
		[ -z "$PATH" ] && PATH="$p" || PATH="$p:$PATH"
	fi
done

# Paths as defined in the /etc/profile.d scripts:
if [ -d /etc/profile.d ]; then
	for s in /etc/profile.d/*.sh; do
		[ -r "$s" ] && . "$s"
	done
fi

# Colorgcc (dunno why they don't dump a script in /etc/profile.d):
[ -d /usr/lib/colorgcc/bin ] && PATH="/usr/lib/colorgcc/bin:$PATH"

# User specific paths: local bin, gems, cabal:
[ -d ~/.local/bin ]          && PATH="$HOME/.local/bin:$PATH"
[ -d ~/.cabal/bin ]          && PATH="$HOME/.cabal/bin:$PATH"
[ -d ~/.gem/ruby/2.1.0/bin ] && PATH="$HOME/.gem/ruby/2.1.0/bin:$PATH"

# User specific paths: Altera (Quartus, ModelSim):
# - user is recommended to be in 'plugdev' group, for USB devices
# - quartus starts Quartus, vsim starts ModelSim
dir_altera="$HOME/.local/bin/altera"
if [ -d "$dir_altera" ]; then
	PATH="$dir_altera/quartus/bin:$PATH"      # Quartus
	PATH="$dir_altera/modelsim_ase/bin:$PATH" # ModelSim
	PATH="$dir_altera/nios2eds/bin:$PATH"     # NIOS2
	PATH="$dir_altera/nios2eds/bin/gnu/H-i686-pc-linux-gnu/bin:$PATH"
	PATH="$dir_altera/nios2eds/sdk2/bin:$PATH"
fi
unset dir_altera

export PATH

# Set vim as default text editor:
export EDITOR='/usr/bin/vim'

# Set XDG variables:
export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME=~/.cache
export XDG_DATA_HOME=~/.local/share

# Fix various applications to respect XDG:
export VIMINIT="source $XDG_CONFIG_HOME/vim/vimrc"
export XINITRC=$XDG_CONFIG_HOME/X11/xinitrc
export XAUTHORITY=$XDG_CONFIG_HOME/X11/Xauthority

# Set colours for less, man:
if [ "$TERM" = 'linux' ]; then
	export LESS_TERMCAP_mb=$(printf "\033[34m")
	export LESS_TERMCAP_md=$(printf "\033[31m")
	export LESS_TERMCAP_me=$(printf "\033[0m")
	export LESS_TERMCAP_se=$(printf "\033[0m")
	export LESS_TERMCAP_so=$(printf "\033[30;43m")
	export LESS_TERMCAP_ue=$(printf "\033[0m")
	export LESS_TERMCAP_us=$(printf "\033[32m")
else
	export LESS_TERMCAP_mb=$(printf "\033[1;34m")
	export LESS_TERMCAP_md=$(printf "\033[38;5;9m")
	export LESS_TERMCAP_me=$(printf "\033[0m")
	export LESS_TERMCAP_se=$(printf "\033[0m")
	export LESS_TERMCAP_so=$(printf "\033[30;43m")
	export LESS_TERMCAP_ue=$(printf "\033[0m")
	export LESS_TERMCAP_us=$(printf "\033[38;5;10m")
fi
