#!/bin/sh
# Sets environment variables before logging into the shell.
# Written by ayekat on a frustrating evening in september 2014.


# ------------------------------------------------------------------------------
# PATH {{{

# Adds directory to the PATH variable, with (hopefully) all necessary checks:
add_to_path() {
	[ -d "$1" ] || return
	[ -z "$PATH" ] && PATH="$1" && return
	ifs_old="$IFS"
	IFS=:
	for i in $PATH; do
		[ "$1" = "$i" ] && return
		[ -h "$1" ] && [ "$(readlink -f "$1")" = "$i" ] && return
	done
	PATH="$1:$PATH"
	IFS="$ifs_old"
	unset ifs_old
}

# User specific paths:
for p in "/usr/lib/colorgcc/bin" \
         "$HOME/.local/bin" \
         "$HOME/.cabal/bin" \
         "$HOME/.gem/ruby/2.1.0/bin"
do
	add_to_path "$p"
done

# Altera (Quartus, ModelSim):
# - user is recommended to be in 'plugdev' group, for USB devices
# - quartus starts Quartus, vsim starts ModelSim
dir_altera="$HOME/.local/bin/altera"
if [ -d "$dir_altera" ]; then
	for p in "$dir_altera/quartus/bin" \
	         "$dir_altera/modelsim_ase/bin" \
	         "$dir_altera/nios2eds/bin" \
	         "$dir_altera/nios2eds/bin/gnu/H-i686-pc-linux-gnu/bin" \
	         "$dir_altera/nios2eds/sdk2/bin"
	do
		add_to_path "$p"
	done
fi
unset dir_altera

unset -f add_to_path
export PATH

# }}}
# ------------------------------------------------------------------------------

# Set vim as default text editor:
export EDITOR='/usr/bin/vim'
export VISUAL='/usr/bin/vim'
export PAGER='/usr/bin/less'

# Set XDG variables:
export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME=~/.cache
export XDG_DATA_HOME=~/.local/share

# Fix various applications to respect XDG:
export VIMINIT="source $XDG_CONFIG_HOME/vim/vimrc"    # vim
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"         # xinit (startx ignores)
export XAUTHORITY="$XDG_CONFIG_HOME/X11/Xauthority"   # startx
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"             # gpg
export PGPPATH="$XDG_CONFIG_HOME/gnupg"               # mutt (pgp)
export TASKDATA="$XDG_DATA_HOME/task"                 # task-warrior
export TASKRC="$XDG_CONFIG_HOME/task/taskrc"          # task-warrior
export RXVT_SOCKET="$HOME/.urxvtd.sock"               # urxvtd
export LESSHISTFILE="$XDG_CACHE_HOME/lesshist"        # less
export PASSWORD_STORE_DIR="$XDG_CONFIG_HOME/pass"     # pass
export GIMP2_DIRECTORY="$XDG_CONFIG_HOME/gimp"        # gimp
export MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"        # mplayer

# Set colours for less, man:
if [ "$TERM" = 'linux' ]; then
	export LESS_TERMCAP_mb=$(printf "\033[34m")
	export LESS_TERMCAP_md=$(printf "\033[31m")
	export LESS_TERMCAP_me=$(printf "\033[0m")
	export LESS_TERMCAP_se=$(printf "\033[0m")
	export LESS_TERMCAP_so=$(printf "\033[30;43m")
	export LESS_TERMCAP_ue=$(printf "\033[0m")
	export LESS_TERMCAP_us=$(printf "\033[32m")
else
	export LESS_TERMCAP_mb=$(printf "\033[1;34m")
	export LESS_TERMCAP_md=$(printf "\033[38;5;9m")
	export LESS_TERMCAP_me=$(printf "\033[0m")
	export LESS_TERMCAP_se=$(printf "\033[0m")
	export LESS_TERMCAP_so=$(printf "\033[30;43m")
	export LESS_TERMCAP_ue=$(printf "\033[0m")
	export LESS_TERMCAP_us=$(printf "\033[38;5;10m")
fi
