#!/usr/bin/env sh
# Actions performed when logging into a shell.
# Written by ayekat on a cold sunday afternoon in November 2014.

# ------------------------------------------------------------------------------
# ENVIRONMENT {{{

# tmux seems to overwrite the $PATH variable; regenerate environment:
if [ -n "$TMUX" ]; then
	. $XDG_CONFIG_HOME/sh/environment
fi

# }}}
# ------------------------------------------------------------------------------
# LOGO {{{

printlogo() {
	case "$1" in
		debian)
			printf "\033[31m                             \n"
			printf         "          .xd§PVkbxc.        \n"
			printf         "         xP*'      'Vb.      \n"
			printf         "       'd'     .,.   V.\`     \n"
			printf         "       (*    .'   .  ::      \033[0m `uname -s -r`\n"
			printf "\033[31m       #     #      ,7       \033[0m on `uname -n`\n"
			printf "\033[31m       V,     *-__ -'        \n"
			printf         "       'qb                   \n"
			printf         "         *:,                 \n"
			printf         "           '-.               \n"
			printf         "               '             \n"
			printf  "\033[0m                             \n"
			;;
		arch|archarm)
			printf "\033[34m                             \n"
			printf         "              /\\            \n"
			printf         "             /AA\\           \n"
			printf         "            .'YAA\\          \n"
			printf         "           /AAAAAA\\         \033[0m `uname -s -r`\n"
			printf "\033[34m          /AAAAAAAA\\        \033[0m on `uname -n`\n"
			printf "\033[34m         /AAA/  \\AAA\\      \n"
			printf         "        /AAA|    |AAP\\      \n"
			printf         "       /AAAY\\    /YAAa_     \n"
			printf         "      />*'          '*<\\    \n"
			printf         "     ^                  ^    \n"
			printf  "\033[0m                             \n"
			;;
		darwin)
			printf "\033[32m                  .          \n"
			printf         "               .dA'          \n"
			printf         "               AP'           \n"
			printf         "        .dAAbx.,dAAAb.       \n"
			printf "\033[33m       dAAAAAAAAAAAAP        \033[0m `uname -s -r`\n"
			printf "\033[31m      :AAAAAAAAAAAAA         \033[0m on `uname -n`\n"
			printf "\033[31m      'AAAAAAAAAAAAA.        \n"
			printf "\033[35m       YAAAAAAAAAAAAAx.      \n"
			printf "\033[34m        \\AAAAAAAAAAAAP      \n"
			printf "\033[36m         '<AV*''*\\AP'       \n"
			printf         "                             \n"
			printf  "\033[0m                             \n"
			;;
		gentoo)
			printf "\033[36m           __                \n"
			printf         "       .-d§§§§§bc,           \n"
			printf         "      /§§§§§*\"*Y§§§c.       \n"
			printf         "     (§§§§§§.   )§§§§b,      \n"
			printf         "     '(§§§§§§bxxI§§§§§§b     \033[0m $(uname -s -r)\n"
			printf "\033[36m       \`\">§§§§§§§§§§§§§§)  \033[0m on $(uname -n)\n"
			printf "\033[36m       .?§§§§§§§§§§§§§P\`    \n"
			printf         "     .A§§§§§§§§§§§§§*'       \n"
			printf         "     §§§§§§§§§§§\$*\`        \n"
			printf         "     V§§§§§§§*'\`            \n"
			printf         "       \`\"\`\`              \n"
			printf  "\033[0m                             \n"
			;;
		ubuntu)
			printf "\033[35m                              \n"
			printf         "          .-x#XXX#:-.         \n"
			printf         "       .dXXXXXXXXY*\"<Xb.     \n"
			printf         "      dXXXXP(^\`\`\`'._.XXXb  \n"
			printf         "     JXXXP' _\\\\a#a,. 'VXXXA \n"
			printf         "    |XP\"*. .XXXXXXD. 'XXXX)  \033[0m $(uname -s -r)\n"
			printf "\033[35m    (X.  ; (XXXXXXXT''XXXX)   \033[0m on $(uname -n)\n"
			printf "\033[35m    'XXXX. \`\\XXXXXP  .XXXX' \n"
			printf         "     *XXXXb./ \`\` ,·-dXXXX/  \n"
			printf         "      'YXXXXX#a-a|  .XXY'     \n"
			printf         "        '+XXXXXXXXX#XP'       \n"
			printf         "           \`'\"***\"'\`      \n"
			printf "\033[0m                               \n"
			;;
	esac
}
printlogo "$OS_RELEASE"

# }}}
# ------------------------------------------------------------------------------
# TODO {{{

# Display the todo file in the home directory:
[ -e "$HOME"/TODO ] && { echo; cat "$HOME"/TODO; echo; }

# }}}
# ------------------------------------------------------------------------------
