#!/bin/sh -

set -uf

xdg_download_dir()
(
	UDF=$XDG_CONFIG_HOME/user-dirs.dirs
	unset XDG_DOWNLOAD_DIR
	# shellcheck disable=SC1090
	test -f "$UDF" && test -r "$UDF" && . "$UDF"
	printf '%s' "${XDG_DOWNLOAD_DIR:-~/Downloads}"
)

MOZDIR=${MOZDIR:-$XDG_STATE_HOME/mozilla}
XDG_DOWNLOAD_DIR=$(xdg_download_dir) || exit $?
MOZDIR_DOWNLOAD_DIR=$MOZDIR/${XDG_DOWNLOAD_DIR#$HOME}
readonly MOZDIR XDG_DOWNLOAD_DIR MOZDIR_DOWNLOAD_DIR

mkdir -p "$MOZDIR"
ln -sf "$XDG_DOWNLOAD_DIR" "$MOZDIR_DOWNLOAD_DIR"

exec env HOME="$MOZDIR" MOZ_USE_XINPUT2=1 unwrap firefox "$@"
