#!/bin/sh
# Xinit ressource file for starting a stand-alone WM
# Written by ayekat on a rainy day in october 2012

# Set up logging:
session_logdir="$XDG_LOG_HOME"/X11/xinit/"$DISPLAY"
session_logfile="$session_logdir"/"$(date +%s)".log
mkdir -p "$session_logdir"
ln -sf "$session_logfile" "$session_logdir"/latest
exec 1>"$session_logfile" 2>&1

# Make sure we are in the home directory, to avoid weird default working
# directory paths when opening a shell under X:
cd || exit 1

# Load system xinitrc snippets:
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		if [ -r "$f" ]; then
			. "$f"
		fi
	done
	unset f
fi

# Load user xinitrc snippets:
if [ -d "$XDG_CONFIG_HOME"/X11/xinitrc.d ]; then
	for f in "$XDG_CONFIG_HOME"/X11/xinitrc.d/?*.sh; do
		if [ -r "$f" ]; then
			. "$f"
		fi
	done
	unset f
fi

# Load user X profile:
if [ -e "$XDG_CONFIG_HOME"/X11/xprofile ]; then
	if [ -r "$XDG_CONFIG_HOME"/X11/xprofile ]; then
		. "$XDG_CONFIG_HOME"/X11/xprofile
	fi
fi

# Launch window manager:
exec "${wm:-karuiwm}"
